spring:
  application:
    name: exerc5-itau-unibanco
    version: v0.0.1
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASS:password}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 5000
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/itauunibancodb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080
swagger:
  application:
    name: Produto MS - Ita√∫ Unibanco